### ISSUE TITLE
Error: Unbound value Ocamlbuild_pack.Flags.mark_tag_used

### ISSUE THREAD

**Issue by mustakimur** [maurer/symfuzz#1]
$symfuzz/libinput$ sudo make install
ocamlbuild -no-links -X unittest libinput.cma libinput.cmxa
- /usr/bin/ocamlopt unix.cmxa -I /usr/lib/ocaml/ocamlbuild /usr/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /usr/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
  File "myocamlbuild.ml", line 7, characters 20-55:
  Error: Unbound value Ocamlbuild_pack.Flags.mark_tag_used
  Command exited with code 2.
  Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
  Makefile:22: recipe for target 'lib' failed
  make: **\* [lib] Error 10
  I found this error. Could you please help me to figure it out why?

**Comment by maurer** [comment]
Please review the [README](https://github.com/maurer/symfuzz/blob/master/README.md), specifically the part about OCaml > 4.02.1.

`mark_tag_used` was added in [2013](https://github.com/ocaml/ocaml/commit/e69107143dacf2511ec6278269875aa4cdbeaf8d) and has been present in OCaml for a while.

If you are still having troubles, please post the contents of `ocaml -version` (this should be a number > 4.02.1)
